version : "3"

services:
    app:
        build:
            context: .
        ports:
            - "8000:8000"
        volumes:
            - .:/app
        command: >
            sh -c "python /app/src/manage.py migrate && python /app/src/manage.py runserver 0.0.0.0:8000"
